### ISSUE TITLE
钓鱼结果前添加用户名

### ISSUE THREAD

**Issue by haitang000** [CrashVibe/U1bot#105]
有时候群友用得太频繁了，很多人的钓鱼结果混在一起，加上就不会这样了

**Comment by haitang000** [comment]
背包和统计信息没加上呢 qwq

**Comment by wling-art** [comment]
呃，好吧，我有空会加进去滴

**Comment by wling-art** [comment]
fix
https://github.com/CrashVibe/U1bot/commit/4b5d3ca3464f69a257939c1a809f16817352ab9c
