### ISSUE TITLE
回声洞添加匿名发布

### ISSUE THREAD

**Issue by haitang000** [CrashVibe/U1bot#93]
可以使用 「匿名回声洞 ＜内容＞」来发送匿名回声洞，在姚奕发出回声洞内容时将「发布人」中的QQ号改为「匿名用户」

**Comment by wling-art** [comment]
问题在于如果匿名乱发怎么办，审核系统貌似有点麻烦

**Comment by wling-art** [comment]
> 审核()

我抗议你的建议，不审核了，但用户信息照样保存至数据库
~~其实就是懒~~

**Comment by wling-art** [comment]
fix
https://github.com/CrashVibe/U1bot/commit/47325d615286b0609e2b82190a67224e8bf5f9e9
